baseURL = "https://nzinfo.github.io/public/"
languageCode = "zh-cn"
title = "nzinfo's Blog"
theme = "simpleness"

[markup]
  [markup.asciidocExt]
    backend = "html5"
    extensions = ["asciidoctor-html5s", "asciidoctor-diagram"]
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]